//! JSON Schema for `config.toml`, for editor completion (`sverb config --schema`).
//!
//! The committed copy is `docs/config.schema.json`; a test fails when it is stale.
//! Regenerate it with `SVERB_BLESS_SCHEMA=1 cargo test -p sverb-core config::schema`.
//!
//! M7-07: [`markdown`] renders the same schema (descriptions, types, defaults, when a
//! change applies) as `docs/config.md`, regenerated by the same command.

use std::fmt::Write as _;

use serde_json::Value;

use super::{APPLY_SCOPES, Config, DEFAULT_CONFIG_TOML};

/// The schema as a `serde_json` value.
pub fn json_schema_value() -> serde_json::Value {
    schemars::schema_for!(Config).to_value()
}

/// The schema as pretty-printed JSON with a trailing newline.
pub fn json_schema() -> String {
    // Serializing a `serde_json::Value` can't fail.
    let mut out = serde_json::to_string_pretty(&json_schema_value()).unwrap_or_default();
    out.push('\n');
    out
}

// M7-07
/// The tables of `config.toml`, in file order.
const TABLES: &[&str] = &[
    "general",
    "ui",
    "terminal",
    "clipboard",
    "ssh",
    "recording",
    "history",
    "sync",
    "logs",
];

// M7-07
/// `docs/config.md`: every key of `config.toml` with its type, default, when a change
/// applies and its description, generated from the JSON schema.
pub fn markdown() -> String {
    let schema = json_schema_value();
    let resolve = |v: &Value| -> Value {
        match v.get("$ref").and_then(Value::as_str) {
            Some(r) => r
                .strip_prefix("#/")
                .map(|p| p.split('/').fold(&schema, |v, seg| &v[seg]))
                .cloned()
                .unwrap_or(Value::Null),
            None => v.clone(),
        }
    };
    let mut out = String::new();
    out.push_str(
        "<!-- Generated from the config model (crates/sverb-core/src/config). Do not edit:\n     \
         run `SVERB_BLESS_SCHEMA=1 cargo test -p sverb-core config::schema` to regenerate. -->\n\n\
         # Configuration reference\n\n\
         sverb reads one TOML file, `config.toml`, from the config directory \
         (`~/.config/sverb/` on Linux, `~/Library/Application Support/sverb/` on macOS, \
         `%APPDATA%\\sverb\\` on Windows, or `$SVERB_HOME/config` when `SVERB_HOME` is set; \
         `sverb config --path` prints it). Every key is optional. Unknown keys are errors \
         with a \"did you mean\" hint, and an invalid file keeps the last good config in \
         effect (a toast reports the problem). The file is reloaded when it changes; the \
         *Applies* column says when a new value takes effect.\n\n\
         - `sverb config --check` validates the file, `sverb config --print-default` prints \
         the defaults below as a commented file.\n\
         - `docs/config.schema.json` is the JSON schema, for editor completion (for example \
         with taplo: `#:schema ./config.schema.json`).\n\
         - Keys marked *spec addition* are not in SPEC.md draft v0.3; they are recorded in \
         the SPEC decisions log.\n",
    );
    let additions = [
        "ssh.auto_reconnect",
        "recording.retention_days",
        "history.ghost_text",
        "ui.ascii",
        "ui.reduce_motion",
    ];
    for table in TABLES {
        let prop = &schema["properties"][table];
        let def = resolve(prop);
        let _ = writeln!(out, "\n## `[{table}]`\n");
        if let Some(d) = prop.get("description").and_then(Value::as_str) {
            let _ = writeln!(out, "{d}\n");
        }
        out.push_str("| Key | Type | Default | Applies | Description |\n|---|---|---|---|---|\n");
        let props = def.get("properties").and_then(Value::as_object);
        // APPLY_SCOPES lists the keys in struct (file) order.
        for (path, scope) in APPLY_SCOPES {
            let Some(key) = path
                .strip_prefix(table)
                .and_then(|rest| rest.strip_prefix('.'))
            else {
                continue;
            };
            let Some(field) = props.and_then(|p| p.get(key)) else {
                continue;
            };
            let target = resolve(field);
            let ty = match target.get("oneOf").and_then(Value::as_array) {
                Some(alts) => alts
                    .iter()
                    .filter_map(|a| a.get("const").and_then(Value::as_str))
                    .map(|c| format!("`\"{c}\"`"))
                    .collect::<Vec<_>>()
                    .join(" \\| "),
                None => match target.get("type") {
                    Some(Value::String(t)) => t.clone(),
                    _ => "value".to_owned(),
                },
            };
            let default = field
                .get("default")
                .map(|d| code_cell(&toml_value(d)))
                .unwrap_or_default();
            let mut desc = field
                .get("description")
                .and_then(Value::as_str)
                .unwrap_or("")
                .replace('|', "\\|")
                .replace('\n', " ");
            if additions.contains(path) {
                desc.push_str(" *(spec addition)*");
            }
            let _ = writeln!(
                out,
                "| `{key}` | {ty} | {default} | {} | {desc} |",
                scope.describe()
            );
        }
    }
    out.push_str(
        "\n## `[keys.<mode>]`\n\n\
         Key binding overrides, one table per mode: `[keys.terminal]` (after the leader, in \
         every mode; the name is historical), `[keys.normal]` (sverb views focused) and \
         `[keys.copy]` (copy mode). Each entry maps a chord (`\"ctrl-k\"`, `\"p\"`, \
         `\"shift-tab\"`) to an action name; `\"none\"` unbinds a default. Changes apply \
         live. The actions and their default keys are listed in \
         [keybindings.md](keybindings.md).\n\n\
         ## The default file\n\n```toml\n",
    );
    out.push_str(DEFAULT_CONFIG_TOML);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("```\n");
    out
}

/// Inline code for a table cell: `|` escaped, a longer fence around backticks.
fn code_cell(text: &str) -> String {
    let text = text.replace('|', "\\|");
    if text.contains('`') {
        format!("`` {text} ``")
    } else {
        format!("`{text}`")
    }
}

/// A JSON default as TOML-ish text (strings quoted, booleans and numbers bare).
fn toml_value(v: &Value) -> String {
    match v {
        Value::String(s) => format!("{s:?}"),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use serde_json::Value;

    use super::*;

    fn committed_path() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/config.schema.json")
    }

    /// T-21: `docs/config.schema.json` matches the model.
    #[test]
    fn t21_schema_is_fresh() {
        let generated = json_schema();
        if std::env::var_os("SVERB_BLESS_SCHEMA").is_some() {
            std::fs::write(committed_path(), &generated).unwrap();
        }
        let committed = std::fs::read_to_string(committed_path()).unwrap_or_default();
        assert!(
            committed == generated,
            "docs/config.schema.json is stale; run `SVERB_BLESS_SCHEMA=1 cargo test -p sverb-core config::schema`"
        );
    }

    // M7-07
    /// `docs/config.md` matches the model, and lists every key.
    #[test]
    fn config_reference_is_fresh() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/config.md");
        let generated = markdown();
        if std::env::var_os("SVERB_BLESS_SCHEMA").is_some() {
            std::fs::write(&path, &generated).unwrap();
        }
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            committed == generated,
            "docs/config.md is stale; run `SVERB_BLESS_SCHEMA=1 cargo test -p sverb-core config::schema`"
        );
        for (key, _) in APPLY_SCOPES.iter().filter(|(k, _)| *k != "keys") {
            let (_, name) = key.split_once('.').unwrap();
            assert!(generated.contains(&format!("| `{name}` |")), "{key}");
        }
    }

    /// Minimal structural JSON Schema check (the `jsonschema` crate isn't vendored):
    /// `type`, `properties`, `additionalProperties: false`, `enum`, `$ref`, `minimum`.
    fn check(schema: &Value, root: &Value, value: &Value, path: &str, errors: &mut Vec<String>) {
        if let Some(r) = schema.get("$ref").and_then(Value::as_str) {
            let target = r
                .strip_prefix("#/")
                .map(|p| p.split('/').fold(root, |v, seg| &v[seg]))
                .unwrap_or(&Value::Null);
            return check(target, root, value, path, errors);
        }
        if let Some(all) = schema.get("allOf").and_then(Value::as_array) {
            for s in all {
                check(s, root, value, path, errors);
            }
        }
        if let Some(any) = schema
            .get("oneOf")
            .or_else(|| schema.get("anyOf"))
            .and_then(Value::as_array)
        {
            let ok = any.iter().any(|s| {
                let mut e = Vec::new();
                check(s, root, value, path, &mut e);
                e.is_empty()
            });
            if !ok {
                errors.push(format!("{path}: matches none of the alternatives"));
            }
        }
        if let Some(c) = schema.get("const")
            && c != value
        {
            errors.push(format!("{path}: expected {c}"));
        }
        if let Some(e) = schema.get("enum").and_then(Value::as_array)
            && !e.contains(value)
        {
            errors.push(format!("{path}: {value} not in enum"));
        }
        if let Some(t) = schema.get("type") {
            let types: Vec<&str> = match t {
                Value::String(s) => vec![s.as_str()],
                Value::Array(a) => a.iter().filter_map(Value::as_str).collect(),
                _ => vec![],
            };
            let ok = types.iter().any(|t| match *t {
                "object" => value.is_object(),
                "string" => value.is_string(),
                "boolean" => value.is_boolean(),
                "integer" => value.is_u64() || value.is_i64(),
                "number" => value.is_number(),
                "array" => value.is_array(),
                "null" => value.is_null(),
                _ => false,
            });
            if !ok {
                errors.push(format!("{path}: {value} is not of type {t}"));
            }
        }
        if let (Some(min), Some(v)) = (
            schema.get("minimum").and_then(Value::as_f64),
            value.as_f64(),
        ) && v < min
        {
            errors.push(format!("{path}: {v} < minimum {min}"));
        }
        if let Some(obj) = value.as_object() {
            let props = schema.get("properties").and_then(Value::as_object);
            for (k, v) in obj {
                let sub = props.and_then(|p| p.get(k));
                match (sub, schema.get("additionalProperties")) {
                    (Some(s), _) => check(s, root, v, &format!("{path}.{k}"), errors),
                    (None, Some(Value::Bool(false))) => {
                        errors.push(format!("{path}.{k}: additional property not allowed"));
                    }
                    (None, Some(ap @ Value::Object(_))) => {
                        check(ap, root, v, &format!("{path}.{k}"), errors);
                    }
                    _ => {}
                }
            }
        }
    }

    /// T-22: the schema accepts the defaults, and rejects a wrong type and an unknown key.
    #[test]
    fn t22_schema_accepts_defaults() {
        let schema = json_schema_value();
        let defaults = serde_json::to_value(Config::default()).unwrap();
        let mut errors = Vec::new();
        check(&schema, &schema, &defaults, "$", &mut errors);
        assert!(errors.is_empty(), "{errors:#?}");

        let mut bad = defaults.clone();
        bad["ssh"]["keepalive_secs"] = Value::String("x".into());
        bad["ssh"]["keepalive_sec"] = Value::from(1);
        bad["ssh"]["host_key_policy"] = Value::String("yolo".into());
        let mut errors = Vec::new();
        check(&schema, &schema, &bad, "$", &mut errors);
        assert_eq!(errors.len(), 3, "{errors:#?}");

        // Every top-level property documents its default.
        let props = schema["properties"].as_object().unwrap();
        for (k, v) in props {
            assert!(v.get("description").is_some(), "{k} has no description");
        }
    }
}
