//! Security policy for what remote output may do (SPEC §7.3, §17).
//!
//! The emulator only *reports* requests (OSC 52 writes, titles, cwd). Applying the user's policy
//! is the UI's job. The invariants enforced here, inside the emulator, are:
//! - OSC 52 clipboard **reads are always denied**: nothing is ever written back to the remote;
//! - titles are capped at [`MAX_TITLE_CHARS`] and stripped of control characters;
//! - query replies (DA, DSR, color queries) are generated by the emulator from its own state,
//!   never echoed from remote input.

/// Maximum length of a window/tab title, in chars (SPEC §17).
pub const MAX_TITLE_CHARS: usize = 256;

/// Maximum length of a reported OSC 7 working directory, in chars.
pub const MAX_CWD_CHARS: usize = 4096;

/// Maximum accepted size of a single OSC 52 write payload (decoded text, in bytes).
///
/// Larger requests are dropped instead of being reported, so a remote can't make the UI hold
/// arbitrarily large clipboard prompts.
pub const MAX_CLIPBOARD_WRITE_BYTES: usize = 1024 * 1024;

/// `clipboard.allow_remote_write` (SPEC §7.3, §15).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum ClipboardWritePolicy {
    /// Drop every OSC 52 write.
    Never,
    /// Ask the user each time (default).
    #[default]
    Ask,
    /// Relay writes without asking.
    Always,
}

/// What the UI should do with an OSC 52 write request under a policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClipboardDecision {
    Drop,
    Prompt,
    Relay,
}

impl ClipboardWritePolicy {
    /// Decide what to do with a write request.
    #[must_use]
    pub fn decide(self) -> ClipboardDecision {
        match self {
            Self::Never => ClipboardDecision::Drop,
            Self::Ask => ClipboardDecision::Prompt,
            Self::Always => ClipboardDecision::Relay,
        }
    }
}

/// Strip control characters and cap the length at `max` chars.
#[must_use]
pub fn sanitize_text(input: &str, max: usize) -> String {
    input
        .chars()
        .filter(|c| !c.is_control())
        .take(max)
        .collect()
}

/// Sanitize a title from OSC 0/2: control characters removed, at most [`MAX_TITLE_CHARS`] chars.
#[must_use]
pub fn sanitize_title(input: &str) -> String {
    sanitize_text(input, MAX_TITLE_CHARS)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_is_capped_and_cleaned() {
        let raw = format!("a\u{7}b\u{1b}c\u{9b}{}", "x".repeat(10_000));
        let t = sanitize_title(&raw);
        assert!(t.chars().count() <= MAX_TITLE_CHARS);
        assert!(t.starts_with("abc"));
        assert!(!t.chars().any(char::is_control));
    }

    #[test]
    fn policy_decisions() {
        assert_eq!(
            ClipboardWritePolicy::default().decide(),
            ClipboardDecision::Prompt
        );
        assert_eq!(
            ClipboardWritePolicy::Never.decide(),
            ClipboardDecision::Drop
        );
        assert_eq!(
            ClipboardWritePolicy::Always.decide(),
            ClipboardDecision::Relay
        );
    }
}
